# Generated by Django 2.1.4 on 2018-12-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('datedebut', models.CharField(blank=True, db_column='dateDebut', max_length=255, null=True)),
                ('datefin', models.CharField(blank=True, db_column='dateFin', max_length=255, null=True)),
                ('salle', models.CharField(blank=True, max_length=255, null=True)),
                ('nombreplacedispo', models.IntegerField(blank=True, db_column='nombrePlaceDispo', null=True)),
                ('id_1', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ACTIVITE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Animer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_1', models.IntegerField()),
            ],
            options={
                'db_table': 'ANIMER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ARTICLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id_1', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ATELIER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'CONFERENCE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrees',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('dateentree', models.CharField(blank=True, db_column='dateEntree', max_length=50, null=True)),
                ('heureentree', models.CharField(blank=True, db_column='heureEntree', max_length=50, null=True)),
                ('id_1', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ENTREES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstDeType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_1', models.IntegerField()),
            ],
            options={
                'db_table': 'EST_DE_TYPE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GererStock',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_1', models.IntegerField()),
            ],
            options={
                'db_table': 'GERER_STOCK',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(blank=True, max_length=255, null=True)),
                ('mdp', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'MEMBRE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organiser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_1', models.IntegerField()),
            ],
            options={
                'db_table': 'ORGANISER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_1', models.IntegerField()),
                ('placerestante', models.IntegerField(blank=True, db_column='placeRestante', null=True)),
            ],
            options={
                'db_table': 'PARTICIPER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='President',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PRESIDENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RencontreProfessionnelle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'RENCONTRE_PROFESSIONNELLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'RESPONSABLE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Secretaire',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'SECRETAIRE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoireeMiniProjet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'SOIREE_MINI_PROJET',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sorties',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('datesortie', models.CharField(blank=True, db_column='dateSortie', max_length=50, null=True)),
                ('heuresortie', models.CharField(blank=True, db_column='heureSortie', max_length=50, null=True)),
                ('id_1', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SORTIES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TournoisJeuxVideo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'TOURNOIS_JEUX_VIDEO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tresorier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'TRESORIER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeUtilisateur',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'TYPE_UTILISATEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ufr',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'UFR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('mail', models.CharField(blank=True, max_length=250, null=True)),
                ('telephone', models.CharField(blank=True, max_length=10, null=True)),
                ('abonnenewsletter', models.IntegerField(db_column='abonneNewsletter')),
                ('id_1', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'UTILISATEUR',
                'managed': False,
            },
        ),
    ]
